import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Real Estate Ninja',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster toastOptions={{
          style:{
            background: '#332E3C',
            color: '#fff',
            borderRadius: '10px',
            padding: '10px',
          }
        }}/>
        <Navbar/>
                {children}
      </body>
    </html>
  )
}
